name: "SonarCloudWithGitHubActions"

on:
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx jest --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=tu_org_tu_proyecto
            -Dsonar.organization=tu_org
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
